apiVersion: v1
kind: Service
metadata:
  name: service-motd
spec:
  selector:
    app: motd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Port du conteneur dans le pod
  type: ClusterIP
