# Utilisez une image Node.js comme base
FROM node:14

# Créez le répertoire de travail
WORKDIR /app

# Copiez les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application
COPY . .

# Exposez le port spécifié dans la variable d'environnement APP_PORT
EXPOSE $APP_PORT

# Commande de démarrage de l'application
CMD ["node", "index.js"]
